### ISSUE TITLE
Group 2: To-do list

### ISSUE THREAD

**Issue by IrinaSing** [HackYourFutureBelgium/class-13-14#289]
- [ ] [repo](https://github.com/IrinaSing/To-do-list)
- [ ] [live demo](https://_.github.io/_)
- [/planning](https://github.com/_/_/tree/master/planning)
  - [ ] communication plan
  - [ ] constraints
  - [ ] backlog
  - [ ] wireframe
  - [ ] development strategy
  - [ ] retrospective
- [ ] [project board](https://github.com/_/_/projects/1)
